### ISSUE TITLE
New release needed.

### ISSUE THREAD

**Issue by PythonLinks** [Pylons/hypatia#14]
I happily did 
`pip install hypatia`
Mostly worked, and then I had a strange bug in keyword Index.  Turns out that version was released in 2014. 
 
I should have done:
pip install git+https://github.com/Pylon/hypatia#egg=hypatia

I hope this helps someone.

**Comment by bertjwregeer** [comment]
The latest release was done in April: https://pypi.org/project/hypatia/0.4/ and mostly matches what is in the repo minus some spelling mistakes.
